### ISSUE TITLE
Incorrect display of icon inside of LookupField if SVG icons used

### ISSUE THREAD

**Issue by haulmont-git** [cuba-platform/cuba#693]
Details: https://youtrack.cuba-platform.com/issue/PL-10408

![image](https://user-images.githubusercontent.com/1066152/55342525-0a010500-54ba-11e9-8788-ec235fdc3b43.png)

```java
public class ExtAppMainWindow extends AppMainWindow {
    @Inject
    private LookupField demoLookupField;

    @Override
    public void init(Map<String, Object> params) {
        super.init(params);

        demoLookupField.setOptionsEnum(RoleType.class);
        demoLookupField.setOptionIconProvider(item -> {
            RoleType roleType = (RoleType) item;

            if (roleType.ordinal() % 2 == 0) {
                return "icons/alarm.svg";
            }

            return "icons/cloud.svg";
        });
    }
}
```

```css
  .v-filterselect img.v-icon {
    @include box-sizing(border-box);
    max-width: $v-unit-size - ceil($v-unit-size/6);
    max-height: $v-unit-size - ceil($v-unit-size/6);
    padding-top: ceil($v-unit-size/12);
    margin-left: ceil($v-unit-size/12);
  }

  .v-filterselect-suggestmenu .gwt-MenuItem img.v-icon {
    max-width: $v-unit-size - ceil($v-unit-size/3);
  }
```

==Сonclusion:==

SVG icon should have explicit sizes - `width` and `height` attributes

### Test project
[svg-icons.zip](https://github.com/cuba-platform/cuba/files/3199017/svg-icons.zip)

## QA
Platform version: 7.0
Check the installation of the svg icon inside the components:
- `LookupField`
- `LookupPickerField`
- `SearchField`
- `SearchPickerField`

Platform version: 7.1
Check the installation of the svg icon inside the components:
- `LookupField`
- `LookupPickerField`
- `SearchField`
- `SearchPickerField`
- `PickerField`
- `SuggestionPickerField`
